# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D40ae68iCprVAqBmOy_Gyfx1anim-OTK
"""

import streamlit as st
import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image


## page setup ##

st.set_page_config(page_title="Kidney CT Classifier", layout="centered")
st.title("Kidney CT Scan Classifier (Deep Learning)")
st.write("Upload a Kidney CT scan to detect potential abnormalities (Cyst, Tumor, Stone).")


## loading the model ##

@st.cache_resource
def load_model():
    # initializing standard ResNet18
    model = models.resnet18(weights=None)

    old_conv = model.conv1
    model.conv1 = nn.Conv2d(1, old_conv.out_channels, kernel_size=old_conv.kernel_size,
                            stride=old_conv.stride, padding=old_conv.padding, bias=False)

    num_features = model.fc.in_features
    model.fc = nn.Linear(num_features, 1)

    # loading the weights exported from Kaggle
    weights_path = "kidney_resnet18_weights.pt"
    try:
        state_dict = torch.load(weights_path, map_location=torch.device('cpu'))
        model.load_state_dict(state_dict)
    except RuntimeError:
        # fallback
        clean_dict = {k.replace('model.', ''): v for k, v in state_dict.items()}
        model.load_state_dict(clean_dict)

    model.eval()
    return model

model = load_model()



## image preprocessing ##

preprocess = transforms.Compose([
    transforms.Grayscale(num_output_channels=1),
    transforms.Resize((224, 224)),
    transforms.ToTensor(), # converts to 0-1 scale
    transforms.Normalize(mean=[0.5], std=[0.5])
])



## UI ##

st.subheader("Upload Scan")
uploaded_file = st.file_uploader("Choose a CT scan image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Display the uploaded image
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded CT Scan", use_container_width=True)


    ## Prediction ##

    st.subheader("Analysis")

    if st.button("Run AI Diagnosis"):
        with st.spinner("Analyzing scan..."):
            # preparing image tensor
            input_tensor = preprocess(image).unsqueeze(0)

            # predicting
            with torch.no_grad():
                logits = model(input_tensor).squeeze(1)
                prob = torch.sigmoid(logits).item()

            # threshold logic
            # Healthy is class 0, Abnormal is class 1.
            THRESHOLD = 0.50

            if prob >= THRESHOLD:
                label = "Abnormal"
                confidence = prob * 100
                st.error(f"🩺 **Result: {label}**")
                st.info("The detected patterns consistent with Cyst, Tumor, or Stone.")
            else:
                label = "Healthy"
                confidence = (1 - prob) * 100
                st.success(f" **Result: {label}**")
                st.info("No major visible abnormalities detected in this scan.")

            st.progress(prob if prob > THRESHOLD else (1-prob))
            st.write(f"**Confidence Level:** {confidence:.2f}%")


## disclaimer ##
st.markdown("---")
st.caption("Note: This model was trained on a public dataset and is deployed strictly as a learning/portfolio prototype to demonstrate AI application in healthcare. It is NOT a clinical diagnostic tool.")